### ISSUE TITLE
XL Release does not start after copying com.microsoft.tfs.sdk-14.0.3.jar to lib/

### ISSUE THREAD

**Issue by gjvanhalem** [xebialabs-community/xlr-tfs-plugin#3]
When starting the server after I have copied this file, the following error is thrown:

2016-07-18 08:47:43.578 [main] {} INFO  c.x.xlplatform.config.ConfigLoader$ - Loading xl-release.conf
2016-07-18 08:47:43.937 [main] {} INFO  c.x.xlrelease.XLReleaseBootstrapper - XL Release version 5.0.0 (built at 16-04-20 19:52:51)
2016-07-18 08:47:43.939 [main] {} INFO  c.x.xlrelease.XLReleaseBootstrapper - (c) 2012-2016 XebiaLabs, Inc.

2016-07-18 08:47:44.200 [main] {} INFO  c.x.xlrelease.XLReleaseBootstrapper - Reading configuration file from: /opt/xlr/xl-release-5.0.0-server/conf/xl-release-server.conf
2016-07-18 08:47:44.200 [main] {} INFO  c.x.xlrelease.XLReleaseBootstrapper - Starting server...
2016-07-18 08:47:44.399 [main] {} ERROR c.x.xlrelease.XLReleaseBootstrapper - Fatal error starting server
java.lang.NoSuchMethodError: com.google.common.io.Files.asByteSource(Ljava/io/File;)Lcom/google/common/io/ByteSource;
        at com.xebialabs.deployit.ServerConfigFile.readConfigurationFile(ServerConfigFile.java:67) ~[appserver-core-2016.1.0.jar:na]
        at com.xebialabs.deployit.ServerConfigFile.readConfiguration(ServerConfigFile.java:59) ~[appserver-core-2016.1.0.jar:na]
        at com.xebialabs.deployit.ServerConfigFile.loadConfig(ServerConfigFile.java:40) ~[appserver-core-2016.1.0.jar:na]
        at com.xebialabs.deployit.ServerConfigFile.loadConfig(ServerConfigFile.java:35) ~[appserver-core-2016.1.0.jar:na]
        at com.xebialabs.xlrelease.XLReleaseBootstrapper.startServer(XLReleaseBootstrapper.java:106) [server-5.0.0.jar:na]
        at com.xebialabs.xlrelease.XLReleaseBootstrapper.start(XLReleaseBootstrapper.java:76) [server-5.0.0.jar:na]
        at com.xebialabs.xlrelease.XLReleaseBootstrapper.main(XLReleaseBootstrapper.java:49) [server-5.0.0.jar:na]

The weird thing is that is does not occur on every XL Release instance. But I can't find out what is causing this.

**Comment by gjvanhalem** [comment]
I found that com.microsoft.tfs.sdk-14.0.3.jar seems to contain large parts of Google Guava. This is also available as default in XLR (guava-18.0.jar) and both contain the com.google.common.io.Files.class which seems to be the problem. 
But still, I also have an instance of XLR that works fine with this lib. Do I am still not sure what is causing this.

**Comment by jdewinne** [comment]
Hi,

Can you place the jar file in the plugins folder, and see if that works?

Regards,
Joris

**Comment by gjvanhalem** [comment]
I have placed it in its own tfs/ folder. And added that folder to the end of the classpath in the startup script. That solves the problem.
And although I had to change the startup script to accomplish this, I found it to be more fitting than putting a file in the plugins directory that is not a plugin
